apiVersion: v1
kind: Service
metadata:
  name: licitaciones-api
  namespace: licitaciones
  labels:
    app.kubernetes.io/name: licitaciones-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: licitaciones-api
  ports:
    - name: http
      port: 80
      targetPort: http
